version: "3.9"  # optional since v1.27.0
services:
  python:
    build: .
    security_opt:
      - seccomp:unconfined
    devices:
      - /dev/gpiomem:/dev/gpiomem
    environment:
      - PYTHONUNBUFFERED=1
